// AUTO-GENERATED by scripts/generate-art.ts — do not edit manually.

import actorPlayerFerrous from "../../content/art/generated/ferrous-fungal-middle/actor.player.json" with { type: "json" };
import enemyBruteFerrous from "../../content/art/generated/ferrous-fungal-middle/enemy.brute.json" with { type: "json" };
import enemyCasterFerrous from "../../content/art/generated/ferrous-fungal-middle/enemy.caster.json" with { type: "json" };
import enemySkirmisherFerrous from "../../content/art/generated/ferrous-fungal-middle/enemy.skirmisher.json" with { type: "json" };
import featureHoardFerrous from "../../content/art/generated/ferrous-fungal-middle/feature.hoard.json" with { type: "json" };
import itemConsumableFerrous from "../../content/art/generated/ferrous-fungal-middle/item.consumable.json" with { type: "json" };
import itemGearFerrous from "../../content/art/generated/ferrous-fungal-middle/item.gear.json" with { type: "json" };
import itemTreasureFerrous from "../../content/art/generated/ferrous-fungal-middle/item.treasure.json" with { type: "json" };
import npcKeeperFerrous from "../../content/art/generated/ferrous-fungal-middle/npc.keeper.json" with { type: "json" };
import terrainDoorFerrous from "../../content/art/generated/ferrous-fungal-middle/terrain.door.json" with { type: "json" };
import terrainEntranceFerrous from "../../content/art/generated/ferrous-fungal-middle/terrain.entrance.json" with { type: "json" };
import terrainFloorFerrous from "../../content/art/generated/ferrous-fungal-middle/terrain.floor.json" with { type: "json" };
import terrainStairsDownFerrous from "../../content/art/generated/ferrous-fungal-middle/terrain.stairs_down.json" with { type: "json" };
import terrainWallFerrous from "../../content/art/generated/ferrous-fungal-middle/terrain.wall.json" with { type: "json" };
import terrainWaterFerrous from "../../content/art/generated/ferrous-fungal-middle/terrain.water.json" with { type: "json" };
import trapHiddenFerrous from "../../content/art/generated/ferrous-fungal-middle/trap.hidden.json" with { type: "json" };
import trapRevealedFerrous from "../../content/art/generated/ferrous-fungal-middle/trap.revealed.json" with { type: "json" };
import actorPlayerTorchlit from "../../content/art/generated/torchlit-limestone/actor.player.json" with { type: "json" };
import enemyBruteTorchlit from "../../content/art/generated/torchlit-limestone/enemy.brute.json" with { type: "json" };
import enemyCasterTorchlit from "../../content/art/generated/torchlit-limestone/enemy.caster.json" with { type: "json" };
import enemySkirmisherTorchlit from "../../content/art/generated/torchlit-limestone/enemy.skirmisher.json" with { type: "json" };
import featureHoardTorchlit from "../../content/art/generated/torchlit-limestone/feature.hoard.json" with { type: "json" };
import itemConsumableTorchlit from "../../content/art/generated/torchlit-limestone/item.consumable.json" with { type: "json" };
import itemGearTorchlit from "../../content/art/generated/torchlit-limestone/item.gear.json" with { type: "json" };
import itemTreasureTorchlit from "../../content/art/generated/torchlit-limestone/item.treasure.json" with { type: "json" };
import npcKeeperTorchlit from "../../content/art/generated/torchlit-limestone/npc.keeper.json" with { type: "json" };
import terrainDoorTorchlit from "../../content/art/generated/torchlit-limestone/terrain.door.json" with { type: "json" };
import terrainEntranceTorchlit from "../../content/art/generated/torchlit-limestone/terrain.entrance.json" with { type: "json" };
import terrainFloorTorchlit from "../../content/art/generated/torchlit-limestone/terrain.floor.json" with { type: "json" };
import terrainStairsDownTorchlit from "../../content/art/generated/torchlit-limestone/terrain.stairs_down.json" with { type: "json" };
import terrainWallTorchlit from "../../content/art/generated/torchlit-limestone/terrain.wall.json" with { type: "json" };
import terrainWaterTorchlit from "../../content/art/generated/torchlit-limestone/terrain.water.json" with { type: "json" };
import trapHiddenTorchlit from "../../content/art/generated/torchlit-limestone/trap.hidden.json" with { type: "json" };
import trapRevealedTorchlit from "../../content/art/generated/torchlit-limestone/trap.revealed.json" with { type: "json" };
import actorPlayerVoid from "../../content/art/generated/void-ember-lowest/actor.player.json" with { type: "json" };
import enemyBruteVoid from "../../content/art/generated/void-ember-lowest/enemy.brute.json" with { type: "json" };
import enemyCasterVoid from "../../content/art/generated/void-ember-lowest/enemy.caster.json" with { type: "json" };
import enemySkirmisherVoid from "../../content/art/generated/void-ember-lowest/enemy.skirmisher.json" with { type: "json" };
import featureHoardVoid from "../../content/art/generated/void-ember-lowest/feature.hoard.json" with { type: "json" };
import itemConsumableVoid from "../../content/art/generated/void-ember-lowest/item.consumable.json" with { type: "json" };
import itemGearVoid from "../../content/art/generated/void-ember-lowest/item.gear.json" with { type: "json" };
import itemTreasureVoid from "../../content/art/generated/void-ember-lowest/item.treasure.json" with { type: "json" };
import npcKeeperVoid from "../../content/art/generated/void-ember-lowest/npc.keeper.json" with { type: "json" };
import terrainDoorVoid from "../../content/art/generated/void-ember-lowest/terrain.door.json" with { type: "json" };
import terrainEntranceVoid from "../../content/art/generated/void-ember-lowest/terrain.entrance.json" with { type: "json" };
import terrainFloorVoid from "../../content/art/generated/void-ember-lowest/terrain.floor.json" with { type: "json" };
import terrainStairsDownVoid from "../../content/art/generated/void-ember-lowest/terrain.stairs_down.json" with { type: "json" };
import terrainWallVoid from "../../content/art/generated/void-ember-lowest/terrain.wall.json" with { type: "json" };
import terrainWaterVoid from "../../content/art/generated/void-ember-lowest/terrain.water.json" with { type: "json" };
import trapHiddenVoid from "../../content/art/generated/void-ember-lowest/trap.hidden.json" with { type: "json" };
import trapRevealedVoid from "../../content/art/generated/void-ember-lowest/trap.revealed.json" with { type: "json" };

export const GENERATED_RECORDS_BY_PATH: Readonly<Record<string, unknown>> = {
  "ferrous-fungal-middle/actor.player.json": actorPlayerFerrous,
  "ferrous-fungal-middle/enemy.brute.json": enemyBruteFerrous,
  "ferrous-fungal-middle/enemy.caster.json": enemyCasterFerrous,
  "ferrous-fungal-middle/enemy.skirmisher.json": enemySkirmisherFerrous,
  "ferrous-fungal-middle/feature.hoard.json": featureHoardFerrous,
  "ferrous-fungal-middle/item.consumable.json": itemConsumableFerrous,
  "ferrous-fungal-middle/item.gear.json": itemGearFerrous,
  "ferrous-fungal-middle/item.treasure.json": itemTreasureFerrous,
  "ferrous-fungal-middle/npc.keeper.json": npcKeeperFerrous,
  "ferrous-fungal-middle/terrain.door.json": terrainDoorFerrous,
  "ferrous-fungal-middle/terrain.entrance.json": terrainEntranceFerrous,
  "ferrous-fungal-middle/terrain.floor.json": terrainFloorFerrous,
  "ferrous-fungal-middle/terrain.stairs_down.json": terrainStairsDownFerrous,
  "ferrous-fungal-middle/terrain.wall.json": terrainWallFerrous,
  "ferrous-fungal-middle/terrain.water.json": terrainWaterFerrous,
  "ferrous-fungal-middle/trap.hidden.json": trapHiddenFerrous,
  "ferrous-fungal-middle/trap.revealed.json": trapRevealedFerrous,
  "torchlit-limestone/actor.player.json": actorPlayerTorchlit,
  "torchlit-limestone/enemy.brute.json": enemyBruteTorchlit,
  "torchlit-limestone/enemy.caster.json": enemyCasterTorchlit,
  "torchlit-limestone/enemy.skirmisher.json": enemySkirmisherTorchlit,
  "torchlit-limestone/feature.hoard.json": featureHoardTorchlit,
  "torchlit-limestone/item.consumable.json": itemConsumableTorchlit,
  "torchlit-limestone/item.gear.json": itemGearTorchlit,
  "torchlit-limestone/item.treasure.json": itemTreasureTorchlit,
  "torchlit-limestone/npc.keeper.json": npcKeeperTorchlit,
  "torchlit-limestone/terrain.door.json": terrainDoorTorchlit,
  "torchlit-limestone/terrain.entrance.json": terrainEntranceTorchlit,
  "torchlit-limestone/terrain.floor.json": terrainFloorTorchlit,
  "torchlit-limestone/terrain.stairs_down.json": terrainStairsDownTorchlit,
  "torchlit-limestone/terrain.wall.json": terrainWallTorchlit,
  "torchlit-limestone/terrain.water.json": terrainWaterTorchlit,
  "torchlit-limestone/trap.hidden.json": trapHiddenTorchlit,
  "torchlit-limestone/trap.revealed.json": trapRevealedTorchlit,
  "void-ember-lowest/actor.player.json": actorPlayerVoid,
  "void-ember-lowest/enemy.brute.json": enemyBruteVoid,
  "void-ember-lowest/enemy.caster.json": enemyCasterVoid,
  "void-ember-lowest/enemy.skirmisher.json": enemySkirmisherVoid,
  "void-ember-lowest/feature.hoard.json": featureHoardVoid,
  "void-ember-lowest/item.consumable.json": itemConsumableVoid,
  "void-ember-lowest/item.gear.json": itemGearVoid,
  "void-ember-lowest/item.treasure.json": itemTreasureVoid,
  "void-ember-lowest/npc.keeper.json": npcKeeperVoid,
  "void-ember-lowest/terrain.door.json": terrainDoorVoid,
  "void-ember-lowest/terrain.entrance.json": terrainEntranceVoid,
  "void-ember-lowest/terrain.floor.json": terrainFloorVoid,
  "void-ember-lowest/terrain.stairs_down.json": terrainStairsDownVoid,
  "void-ember-lowest/terrain.wall.json": terrainWallVoid,
  "void-ember-lowest/terrain.water.json": terrainWaterVoid,
  "void-ember-lowest/trap.hidden.json": trapHiddenVoid,
  "void-ember-lowest/trap.revealed.json": trapRevealedVoid,
};
